all: genKey main
genKey: genKey.cpp
	g++ genKey.cpp -o genKey.out
	./genKey.out "key.k"
	rm genKey.out
main: main.cpp 
	g++ main.cpp -o main.out
	./main.out "qwe.odt" // Название файла для шифрования
	clear
// Чтобы расшифровать обратно требуется повторно запустить main.out и добавить название файла, как в строчке 7
